name: 'Terraform Apply'
on: workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      working-directory: infracost
    
    permissions: # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve