name: 'Terraform Apply'
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      working-directory: infracost
    
    permissions: # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init

    - name: terraform apply
      uses: dflook/terraform-apply@v1
      continue-on-error: true
      id: first_try
      with:
        path: terraform

    - name: Retry failed apply
      uses: dflook/terraform-apply@v1
      if: ${{ steps.first_try.outputs.failure-reason == 'apply-failed' }}
      with:
        path: terraform
        auto_approve: true